### ISSUE TITLE
Application crashing

### ISSUE THREAD

**Issue by HarshadaMahulkar** [phunware/maas-mapping-android-sdk#52]
Application is crashing when opening Routing Activity, Location Mode activity.
Using Android-mapping-sdk-3.7.1.

**Comment by harishios** [comment]
`2018-11-18 23:22:34.582 31187-31187/com.phunware.kotlin.sample E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.phunware.kotlin.sample, PID: 31187
com.squareup.moshi.JsonDataException: Required property 'movingMaxWindow' missing at $.prismConfig
at com.phunware.location.provider_managed.PrismJsonAdapter.fromJson(PrismJsonAdapter.kt:59)
at com.phunware.location.provider_managed.PrismJsonAdapter.fromJson(PrismJsonAdapter.kt:16)
at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
at com.phunware.location.provider_managed.BuildingJsonAdapter.fromJson(BuildingJsonAdapter.kt:54)
at com.phunware.location.provider_managed.BuildingJsonAdapter.fromJson(BuildingJsonAdapter.kt:14)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
at com.phunware.location.provider_managed.BuildingBundleManager.getBuilding(BuildingBundleManager.java:17)
at com.phunware.location.provider_managed.PwManagedLocationProvider.(PwManagedLocationProvider.java:79)
at com.phunware.location.provider_managed.ManagedProviderFactory.createLocationProvider(ManagedProviderFactory.java:28)
at com.phunware.kotlin.sample.BluedotLocationActivity.setManagedLocationProvider(BluedotLocationActivity.kt:138)
at com.phunware.kotlin.sample.BluedotLocationActivity.access$setManagedLocationProvider(BluedotLocationActivity.kt:53)
at com.phunware.kotlin.sample.BluedotLocationActivity$onPhunwareMapReady$1.onSuccess(BluedotLocationActivity.kt:114)
at com.phunware.kotlin.sample.BluedotLocationActivity$onPhunwareMapReady$1.onSuccess(BluedotLocationActivity.kt:101)
at com.phunware.mapping.manager.PhunwareMapManager.onBuildingOptions(PhunwareMapManager.java:780)
at com.phunware.mapping.manager.PhunwareMapManager.access$1000(PhunwareMapManager.java:85)
at com.phunware.mapping.manager.PhunwareMapManager$4.run(PhunwareMapManager.java:624)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`

**Comment by HarshadaMahulkar** [comment]
Getting following error:
Process: com.example.harshadamahulkar.android_sentara_mapping_poc, PID: 8742
    com.squareup.moshi.JsonDataException: Required property 'movingMaxWindow' missing at $.prismConfig
        at com.phunware.location.provider_managed.PrismJsonAdapter.fromJson(PrismJsonAdapter.kt:59)
        at com.phunware.location.provider_managed.PrismJsonAdapter.fromJson(PrismJsonAdapter.kt:16)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.phunware.location.provider_managed.BuildingJsonAdapter.fromJson(BuildingJsonAdapter.kt:54)
        at com.phunware.location.provider_managed.BuildingJsonAdapter.fromJson(BuildingJsonAdapter.kt:14)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
        at com.phunware.location.provider_managed.BuildingBundleManager.getBuilding(BuildingBundleManager.java:17)
        at com.phunware.location.provider_managed.PwManagedLocationProvider.<init>(PwManagedLocationProvider.java:79)
        at com.phunware.location.provider_managed.ManagedProviderFactory.createLocationProvider(ManagedProviderFactory.java:28)
        at com.example.harshadamahulkar.android_sentara_mapping_poc.LocationModesActivity.setManagedLocationProvider(LocationModesActivity.java:219)
        at com.example.harshadamahulkar.android_sentara_mapping_poc.LocationModesActivity.access$900(LocationModesActivity.java:64)
        at com.example.harshadamahulkar.android_sentara_mapping_poc.LocationModesActivity$5.onSuccess(LocationModesActivity.java:192)
        at com.example.harshadamahulkar.android_sentara_mapping_poc.LocationModesActivity$5.onSuccess(LocationModesActivity.java:178)

**Comment by avakkachen** [comment]
Closing this issue. Will re-open if reproducible in latest version of Location SDK 3.7.5
