### ISSUE TITLE
Routing feature crashes

### ISSUE THREAD

**Issue by HarshadaMahulkar** [phunware/maas-mapping-android-sdk#53]
Hi,

Unable to run Routing feature in Android Mapping SDK.  Its CRASHING !!!  

**Scenario:**
1. Run the code
2. Click on Routing
3. App crashes

**Downloaded source code from**
https://github.com/phunware/maas-mapping-android-sdk

**Crash location:** 

private void setManagedLocationProvider(Building building) {
    ManagedProviderFactory.ManagedProviderFactoryBuilder builder = new ManagedProviderFactory.ManagedProviderFactoryBuilder();
    builder.application(getApplication())
            .context(new WeakReference<Context>(getApplication()))
            .buildingId(String.valueOf(building.getId()));

    ManagedProviderFactory factory = builder.build();

**_PwManagedLocationProvider managedProvider = (PwManagedLocationProvider) factory.createLocationProvider();_**

    mapManager.setLocationProvider(managedProvider, building);
    mapManager.setMyLocationEnabled(true);
}

Error:
com.squareup.moshi.JsonDataException: Required property 'movingMaxWindow' missing at $.prismConfig
        at com.phunware.location.provider_managed.PrismJsonAdapter.fromJson(PrismJsonAdapter.kt:59)
        at com.phunware.location.provider_managed.PrismJsonAdapter.fromJson(PrismJsonAdapter.kt:16)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.phunware.location.provider_managed.BuildingJsonAdapter.fromJson(BuildingJsonAdapter.kt:54)
        at com.phunware.location.provider_managed.BuildingJsonAdapter.fromJson(BuildingJsonAdapter.kt:14)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
        at com.phunware.location.provider_managed.BuildingBundleManager.getBuilding(BuildingBundleManager.java:17)
        at com.phunware.location.provider_managed.PwManagedLocationProvider.<init>(PwManagedLocationProvider.java:79)
        at com.phunware.location.provider_managed.ManagedProviderFactory.createLocationProvider(ManagedProviderFactory.java:28)
        at com.example.harshadamahulkar.android_sentara_mapping_poc.RoutingActivity.setManagedLocationProvider(RoutingActivity.java:245)
        at com.example.harshadamahulkar.android_sentara_mapping_poc.RoutingActivity.access$600(RoutingActivity.java:60)
        at com.example.harshadamahulkar.android_sentara_mapping_poc.RoutingActivity$4.onSuccess(RoutingActivity.java:184)
        at com.example.harshadamahulkar.android_sentara_mapping_poc.RoutingActivity$4.onSuccess(RoutingActivity.java:170)
        at com.phunware.mapping.manager.PhunwareMapManager.onBuildingOptions(PhunwareMapManager.java:780)
        at com.phunware.mapping.manager.PhunwareMapManager.access$1000(PhunwareMapManager.java:85)
        at com.phunware.mapping.manager.PhunwareMapManager$4.run(PhunwareMapManager.java:624)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Also,

We are unable to run the code downloaded from https://github.com/phunware/maas-mapping-android-sdk.  Needed to make below changes and few others in order to run the code
1. Google play services missing from project level gradle file which was required to sync the project
2. Needed to upgrade gradle version
  The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'maas-mapping-android-sdk-master-2' is using version 1.2.30.

**Comment by avakkachen** [comment]
Closing this issue now. Will re-open if reproducible in latest Location SDK 3.7.5.
